### ISSUE TITLE
console.log in published version

### ISSUE THREAD

**Issue by sdacunha** [sj82516/go-singleflight#1]
Hi @sj82516

Appreciate you publishing this package! I noticed in v1.0.1, there are some console.log statements that made it into the build (but I don't see that in this repo). Would it be possible for you to publish a new version without the console.logs or put them behind a flag?

The dest folder has the compiled version that got pushed and includes the console log. A rebuild is probably all thats needed.

**Comment by sj82516** [comment]
Oh I see. I would publish new version without console.log. Thanks for reporting.

**Comment by sj82516** [comment]
solved at 1.0.2

**Comment by sdacunha** [comment]
Thanks for quickly resolving this!
